networks:
  appnet:
    driver: bridge

services:
  nextjs:
    container_name: nextjs-server
    image: ghcr.io/dulranga/glify-cleaning/nextjs-app:latest
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - appnet
    volumes:
      - ./logs/nextjs:/var/log/app
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
        labels: "service=nextjs"
        tag: "{{.ImageName}}|{{.Name}}"

  db:
    image: postgres:16
    container_name: db-server
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgres
    networks:
      - appnet
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
        labels: "service=postgres"
        tag: "{{.ImageName}}|{{.Name}}"

  caddy:
    image: caddy:latest
    container_name: caddy-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./logs/caddy:/var/log/caddy
    networks:
      - appnet
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
        labels: "service=caddy"
        tag: "{{.ImageName}}|{{.Name}}"

  migrations:
    image: ghcr.io/dulranga/glify-cleaning/migrations:latest
    container_name: db-migrations
    env_file: .env
    depends_on:
      - db
    networks:
      - appnet
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: ["npx", "drizzle-kit", "migrate"]
    volumes:
      - ./logs/migrations:/var/log/migrations
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
        labels: "service=migrations"
        tag: "{{.ImageName}}|{{.Name}}"
  
  backup:
    image: postgres:16
    container_name: db-backup
    restart: unless-stopped
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      BACKUP_PASSWORD: ${BACKUP_PASSWORD}
    volumes:
      - /home/glify/.config/rclone:/root/.config/rclone
      - ./backup_script.sh:/usr/local/bin/backup_script.sh
      - ./cron.log:/var/log/cron.log
      - ./logs/backup:/var/log/backup
    networks:
      - appnet
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
        labels: "service=backup"
        tag: "{{.ImageName}}|{{.Name}}"
    command: >
      /bin/bash -c "
        apt-get update &&
        apt-get install -y cron openssl rclone &&
        echo '#!/bin/sh\nexit 0' > /usr/sbin/policy-rc.d &&
        chmod +x /usr/sbin/policy-rc.d &&
        chmod +x /usr/local/bin/backup_script.sh &&
        touch /var/log/cron.log &&
        chmod 666 /var/log/cron.log &&
        cat /proc/self/environ | tr '\\0' '\\n' | sed 's/^/export /' > /tmp/env.sh &&
        echo 'export PATH=/usr/local/bin:/usr/bin:/bin' >> /tmp/env.sh &&
        echo '0 2 * * * . /tmp/env.sh; /usr/local/bin/backup_script.sh >> /var/log/cron.log 2>&1' | crontab - &&
        cron -f
      "
volumes:
  db_data:
  caddy_data:
  caddy_config: