name: Build and Push Next.js Docker Image

on:
    push:
        branches:
            - main

jobs:
    build-and-push-nextjs:
        runs-on: ubuntu-latest

        permissions:
            packages: write
            contents: read

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Nextjs Docker image
              run: |
                  docker build -t ghcr.io/${{ github.repository }}/nextjs-app:latest --progress=plain .

            - name: Push Nextjs Docker image to GHCR
              run: |
                  docker push ghcr.io/${{ github.repository }}/nextjs-app:latest

    build-and-push-migrations:
        runs-on: ubuntu-latest

        permissions:
            packages: write
            contents: read

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build Migrations Docker image
              run: |
                  docker build -t ghcr.io/${{ github.repository }}/migrations:latest -f Dockerfile.migrations --progress=plain .

            - name: Push Migrations Docker image to GHCR
              run: |
                  docker push ghcr.io/${{ github.repository }}/migrations:latest

    deploy:
        runs-on: ubuntu-latest
        needs: [build-and-push-nextjs, build-and-push-migrations]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Connect to VPS and deploy
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                      cd /home/glify/glify-cleaning

                      echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u dulranga --password-stdin

                      docker compose pull --quiet
                      docker compose run --rm migrations
                      docker compose up -d
                      docker image prune -f   # clean old dangling images
